version: "3"

services:
  jenkins:
    container_name: "jenkins"
    build: "./dockerfiles/Dockerfile.jenkins"
    ports:
      - "8080:8080"
      - "5002:5000"
    networks:
      - jenkins
    volumes:
      - ./jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: "postgres:13"
    env_file:
      - .env/pg.env
    networks:
      - jenkins
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  sonarqube:
    build: "./dockerfiles/Dockerfile.sonarqube"
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    env_file:
      - .env/sonar.env
    depends_on:
      - postgres

networks:
  jenkins:
