FROM jenkins/jenkins

USER root

RUN apt-get update && \
  apt-get -qy full-upgrade && \
  apt-get install -qy curl && \
  apt-get install -qy curl && \
  mkdir -p /tmp/download && \
  curl -L https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz | tar -xz -C /tmp/download && \
  rm -rf /tmp/download/docker/dockerd && \
  mv /tmp/download/docker/docker* /usr/local/bin/ && \
  rm -rf /tmp/download && \
  groupadd -g 998 docker && \
  usermod -aG docker jenkins

USER jenkins
